apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: f3mep1xtt-python
  janus-idp.io/tekton: f3mep1xtt-python
  backstage.io/kubernetes-id: f3mep1xtt-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: f3mep1xtt-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
